class Images_const {
   List<String> Anime =[
    'assets/img/a1.json',
    'assets/img/a2.json',
    'assets/img/a3.json',
    'assets/img/a4.json',
    'assets/img/a5.json',
    'assets/img/a6.json',
    'assets/img/a7.json',
    'assets/img/a8.json',
    'assets/img/a1.json',
    'assets/img/a2.json',
    'assets/img/a3.json',
    'assets/img/a4.json',
    'assets/img/a5.json',
    'assets/img/a6.json',
    'assets/img/a7.json',
    'assets/img/a8.json',
    'assets/img/a1.json',
    'assets/img/a2.json',
    'assets/img/a3.json',
    'assets/img/a4.json',
    'assets/img/a5.json',
    'assets/img/a6.json',
    'assets/img/a7.json',
    'assets/img/a8.json',
  ];
}